Shopping card model
AnyaRatusnyak/project-book-store pull request #10
Opened 2024-05-21 21:09 UTC by AnyaRatusnyak

2024-05-22 08:54 UTC, EduarfF approved these changes
1) Maybe add to dto validation with messages. Like: @Min(1, message = "...")

2024-05-22 08:54 UTC, EduarfF commented on src/main/java/projectbookstore/service/impl/CategoryServiceImpl.java
> +        }
Maybe write method for this check

2024-05-23 09:04 UTC, karma-o requested changes
So far so good, please take a look at the comments

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/dto/cartitem/CreateCartItemRequestDto.java
> +@Setter
```suggestion
@Data
```

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/dto/cartitem/UpdateCartItemDto.java
> +@Setter
same

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/dto/cartitem/UpdateCartItemDto.java
> +    private int quantity;
Just to be sure
```suggestion
    @Min(1)
    @NotNull
    private int quantity;
```

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/dto/shoppingcart/ShoppingCartDto.java
> +@Setter
same here

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/model/CartItem.java
> +@Setter
do not forget about equals & hashcode & tostring, jsut exclude lazy fields from it

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/model/CartItem.java
> +    private ShoppingCart shoppingCart;
would also make it lazy

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/model/ShoppingCart.java
> +public class ShoppingCart {
same here

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        cartItem.getBook().setTitle(title);
why do you set book title here?

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
we need to check the existance of shopping cart and books before saving that request

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
also check existance first

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        cartItemRepository.deleteById(id);
same here, always verify passed parameters before using them

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +                .findFirst();
not sure why do you need to check any book titles here, we should always work with ids instead of some other fields that entity may have

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +                .orElseGet(() -> shoppingCartRepository.save(new ShoppingCart(user)));
just create a cart for user during his registration, instead of this

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/model/ShoppingCart.java
> +    private User user;
would be nice to have user map the id of this entity, by using `@MapsId`

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +        return cartItemService.updateCartItem(cartItem, requestDto.getQuantity());
we should verify that this cart item actually belongs to the user that has send this request and not some other user, because that would be insecure

2024-05-23 09:04 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItemService.delete(id);
because of the same reasons as in the comment above
```suggestion
        } else {
            cartItemService.delete(id);
        }
```

2024-05-24 06:46 UTC, AnyaRatusnyak commented on src/main/java/projectbookstore/model/CartItem.java
> +@Setter
I don't want to change it in entity

2024-05-24 09:14 UTC, AnyaRatusnyak commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
I have this check in method addBookToTheShoppingCart in ShoppingCartServiceImpl

2024-05-24 09:20 UTC, AnyaRatusnyak commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
I have this check in method updateCartItem in ShoppingCartServiceImpl

2024-05-24 09:23 UTC, AnyaRatusnyak commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        cartItemRepository.deleteById(id);
I have deleteCartItem method in ShoppingCartServiceImpl with this check

2024-05-24 10:19 UTC, yevheniisynytsia requested changes
Well done! Some small comments to go!

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/mapper/ShoppingCartMapper.java
> +
```suggestion
}
```

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
@AnyaRatusnyak this is not right approach. Let's imagine you'll have 1000 more services that are using `updateCartItem`. All of them will add this check, but it is much easier to add it here, on the lower level.

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        cartItemRepository.deleteById(id);
same here

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +        BookDto bookDto = bookService.findById(requestDto.getBookId());
it is better to work with entities instead of dtos here I think

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +        BookDto bookDto = bookService.findById(requestDto.getBookId());
but in general ok, you can leave it

2024-05-24 10:19 UTC, yevheniisynytsia commented on src/main/java/projectbookstore/service/impl/CartItemServiceImpl.java
> +        return cartItemMapper.toDto(cartItemRepository.save(cartItem));
you also check only if that object is in the shopping cart, but not in db

2024-05-24 15:21 UTC, d1sam requested changes
Good job, but there are some minor changes, that should be done.

2024-05-24 15:21 UTC, d1sam commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-05-24 15:21 UTC, d1sam commented on src/main/java/projectbookstore/service/impl/UserServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2024-05-25 11:07 UTC, d1sam approved these changes
Well done!

2024-05-25 19:09 UTC, merged