Order model hw
AnyaRatusnyak/project-book-store pull request #11
Opened 2024-05-23 21:46 UTC by AnyaRatusnyak

2024-05-27 13:58 UTC, andrii-hoienko requested changes
Nice, left some comments

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/dto/order/CreateOrderRequestDto.java
> +    @NotNull
NotBlank already containts not null

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/dto/order/CreateOrderRequestDto.java
> +    private String shippingAddress;
Add max constraint to align with db

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        order.setTotal(total);
Please move logic of order creation to separate method

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +                + "user id: " + user.getId()));
This should belong to cart service

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(orderRepository.save(order));
What is the reason to save order twice?

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        return dtos;
Could be inline

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        }
Move to separate method

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +                .toList();
```suggestion
        return order.getOrderItems.stream()
                .map(orderItemMapper::toDto)
                .toList();
```

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        return orderItemMapper.toDto(orderItem);
Could be inline

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +                + "order id: " + id));
Code duplication

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findById(id)
```suggestion
        Order order = orderRepository.findById(id, userId)
```

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +
```suggestion
```

2024-05-27 13:58 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/13-create-order-item-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-05-28 09:32 UTC, karma-o approved these changes
GJ! Please take a look at my comments as well before merging

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/dto/category/CreateCategoryRequestDto.java
> +@Setter
why not data?

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/repository/OrderItemRepository.java
> +    Optional<OrderItem> findByIdAndUserId(@Param("itemId") Long itemId,
is it possible to do that without `@Query`?

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/repository/OrderItemRepository.java
> +                                          @Param("userId") Long userId);
BTW, `@Param` is not necessary as long as your method parameter is named the same

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/repository/OrderRepository.java
> +                                         @Param("userId")Long userId);
same here

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCart getExistedCart(Long userId) {
`findShoppingCartByUserId` was a better name, not sure why you renamed it

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +    @Transactional
get operations can be like that to improve performance a bit
```suggestion
    @Transactional(readOnly = true)
```

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +    private Order getExistedOrder(Long orderId,Long userId) {
```suggestion
    private Order getByIdForUser(Long orderId, Long userId) {
```

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/service/impl/OrderServiceImpl.java
> +                    + order.getId() + " for user id: " + userId);
update ex message so that user would know that this order does not belong to him, since that is what we are checking in that method

2024-05-28 09:32 UTC, karma-o commented on src/main/java/projectbookstore/model/Order.java
> +@Setter
Missing equals, hashcode & toString, we should also exclude lazy fields from them, please remember that we have to do that for **all** entity classes

2024-05-28 11:55 UTC, merged