Jwt hw
AnyaRatusnyak/project-book-store pull request #8
Opened 2024-05-14 21:17 UTC by AnyaRatusnyak

2024-05-15 10:19 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-05-15 10:19 UTC, vovasalyha commented on src/main/java/projectbookstore/config/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**", "/swagger-ui/**")
Add also `/v3/api-docs/**`

2024-05-15 10:19 UTC, vovasalyha commented on src/main/java/projectbookstore/dto/UserLoginRequestDto.java
> +    @Length(min = 8, max = 20)
It's better not to mix `jakarta.validation` and `hibernate.validator` annotations. Better use `Size`

2024-05-15 10:19 UTC, vovasalyha commented on src/main/java/projectbookstore/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
```suggestion
            return false;
```

2024-05-15 10:19 UTC, vovasalyha commented on src/main/resources/application.properties
> +jwt.secret=qwertyuioplkjhgfdsazxcvbnm1234567890
It's better to get sensitive properties from system properties and not pushing it to git.

2024-05-16 09:13 UTC, karma-o approved these changes
GJ!

2024-05-16 09:13 UTC, karma-o commented on pom.xml
> +        <jjwt.version>0.11.5</jjwt.version>
```suggestion
        <jwt.version>0.11.5</jwt.version>
```

2024-05-16 09:48 UTC, merged